import { test, expect } from '@playwright/test';
// bag service
test('test', async ({ page }) => {
  const response = await (await fetch(`https://us-central1-easybus-clean-cloud.cloudfunctions.net/testing?realm=JewIJxIl06qRVrOnhBL9&code=store1&method=pos_sign_in`)).json();
  await page.goto(response.url);
  await page.locator('.ant-space-item > .ant-btn').first().click();
  await page.getByText('Bag Service', { exact: true }).click();
  await page.getByText('Bag', { exact: true }).click();
  await page.getByRole('button', { name: 'ADIDAS' }).click();
  await page.getByRole('textbox').nth(1).fill('7');
  await page.getByRole('button', { name: 'Next right' }).click();
  await page.getByRole('button', { name: 'BLACK' }).click();
  await page.getByRole('button', { name: 'Next right' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Interior General Cleaning' }).getByRole('button', { name: 'plus' }).click();
  await page.getByRole('button', { name: 'Next right' }).click();
  await page.getByRole('button', { name: 'right' }).click();
  var currentDate = new Date();
  currentDate.setMonth(currentDate.getMonth() + 1);
  var nextMonth = currentDate.toLocaleString('en-US', { month: '2-digit' });
  await page.getByText('11').click();
  await page.getByRole('button', { name: 'Complete & Close' }).click();
  await page.getByPlaceholder('Search customer, order').click();
  await page.getByText('[1]').click();
  await page.getByRole('button', { name: 'Payment' }).click();
  await page.getByRole('button', { name: 'unpaid' }).click();
  await page.getByRole('button', { name: 'Create order' }).click();
  await page.getByRole('tab', { name: 'Internal receipt' }).click();
  await page.getByRole('heading', { name: '(PENDING)' }).click();
  await page.getByRole('tab', { name: 'Customer receipt' }).click();
  await expect(page.getByRole('tabpanel', { name: 'Customer receipt' }).getByText('Bag x 1 ₹ 30.00')).toBeVisible();
  await expect(page.getByRole('heading', { name: '(PENDING)' })).toBeVisible();
  await expect(page.getByText('Customer name test')).toBeVisible();
  await expect(page.getByText('Customer tel +91 98765 53210')).toBeVisible();
  await expect(page.getByRole('tabpanel', { name: 'Customer receipt' }).getByText('Bag x 1 ₹ 30.00')).toBeVisible();
  await expect(page.getByRole('tabpanel', { name: 'Customer receipt' }).getByText('- Interior General Cleaning ₹ 30.00')).toBeVisible();
  await expect(page.getByRole('tabpanel', { name: 'Customer receipt' }).getByText('- Brand: ADIDAS')).toBeVisible();
  await expect(page.getByRole('tabpanel', { name: 'Customer receipt' }).getByText('- Serial No.: 7')).toBeVisible();
  await expect(page.getByRole('tabpanel', { name: 'Customer receipt' }).getByText('- Colour: BLACK')).toBeVisible();
  await expect(page.getByRole('tabpanel', { name: 'Customer receipt' }).getByText('Outstanding ₹ 30.60')).toBeVisible();
  await expect(page.getByText(`Estimated collection 11/${nextMonth}/2023`)).toBeVisible();
  await page.getByRole('img', { name: 'tag' }).locator('svg').click();
  await expect(page.getByText('test Bag [IC]')).toBeVisible()
});