import { test, expect } from '@playwright/test';
//change home delivery
test('test', async ({ page }) => {
  const response = await (await fetch(`https://us-central1-easybus-clean-cloud.cloudfunctions.net/testing?realm=JewIJxIl06qRVrOnhBL9&code=store1&method=pos_sign_in`)).json();
  await page.goto(response.url);
  await page.getByText('LOAD WASH').click();
  await page.getByText('Load Wash - Per Kg').click();
  await page.getByRole('button', { name: 'plus Add' }).click();
  await page.getByRole('button', { name: '1', exact: true }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: '8', exact: true }).click();
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByPlaceholder('Search customer, order').click();
  await page.getByPlaceholder('Search customer, order').fill('test');
  await page.getByText('[1] test').click();
  await page.getByRole('button', { name: 'calendar' }).click();
  await page.getByText('Home delivery').click();
  await page.getByRole('button', { name: 'right', exact: true }).click();
  var currentDate = new Date();
  currentDate.setMonth(currentDate.getMonth() + 1);
  var nextMonth = currentDate.toLocaleString('en-US', { month: '2-digit' });
  console.log(nextMonth);
  await page.getByText('24', { exact: true }).click();
  await page.getByRole('button', { name: ' Payment' }).click();
  await page.getByRole('button', { name: 'Cash' }).click();
  await page.getByRole('button', { name: 'Create order' }).click();
  await page.getByRole('tab', { name: 'Internal receipt' }).click();
  await expect(page.getByRole('heading', { name: '(PAID)' })).toBeVisible();
  await page.getByRole('tab', { name: 'Customer receipt' }).click();
  await expect(page.getByText('Customer name test')).toBeVisible();
  await expect(page.getByText('Return type Home delivery')).toBeVisible();
  await expect(page.getByText(`Schedule 24/${nextMonth}/2023`)).toBeVisible();
  await expect(page.getByRole('heading', { name: '(PAID)' })).toBeVisible();
  await expect(page.getByText('Customer name test')).toBeVisible();
  await expect(page.getByText('Load Wash - Per Kg ₹ 7.00 x 1/kg ₹ 7.00')).toBeVisible();
  await expect(page.getByText('- Duvets & Bulky Items')).toBeVisible();
  await expect(page.getByRole('tabpanel', { name: 'Customer receipt' }).getByText('- 8 pcs')).toBeVisible();
  await expect(page.getByText('Pay by Cash (₹ 10.20)')).toBeVisible();
});